### ISSUE TITLE
misc info. Intro to archlinuxvn

### ISSUE THREAD

**Issue by icy** [VietFOSS/vn-foss#12]
Hi Viet,

I come to this after reading your post shared on my colleague wall. It's great to see this happens again. I'd like to share some information that would help.

1. You may contact https://github.com/progfou as I recall he spent some years in Vietnam to promote oss.
1. Duy is an active contributor of `git` project: https://github.com/pclouds
1. Nguyen Dai Quy (https://twitter.com/vnpenguin) was one of founders of VnOSS forum . He may help to contact a great network of Vietnamese talents.
1. Larry Nguyen was a founder of VietLUG forum. He is in US but I have lost his contact/email for years. 
1. An Nguyen (saigonlug.org) he was a manager of SaigonLUG. He has a great source of networking too. He would shoot me if I share his email here ;)

Some ArchLinux users and I created a new group `archlinuxvn` in 2011. This group is now active on Telegram (https://t.me/joinchat/EfluHDyAvHhKdi2JmUBPQg). We also have a mailing list (archived here https://l.archlinuxvn.org/archlinuxvn/) but nowadays I rarely see new post: Most people are now on Facebook https://www.facebook.com/groups/archlinuxvn/ .

I'm glad to know you. I would share more if I can recall something useful.

Thanks for your reading,

**Comment by vietlq** [comment]
Hi @icy, thank you for writing! Love your input! I will add your notes accordingly. I already got comments from Duy (pclouds). Please allow some delay as I'm traveling. I will let you know once I finish adding. Thanks again!

**Comment by icy** [comment]
You're welcome.

This project is started by a Vietnamese https://xitrum-framework.github.io/ .  See also https://github.com/ngocdaothanh . He has great works on different languages .

**Comment by icy** [comment]
Close this as I don't have any other good resource so far :)
